In [2]:
%load_ext autoreload
%autoreload 2

In [1]:
# import jax.tools.colab_tpu
# jax.tools.colab_tpu.setup_tpu()

In [1]:
from model import train_model
from constraint_problems import get_problem_from_cnf
from random_walk import moser_walk_sampler
import jax

In [3]:
from pysat.formula import CNF
import glob
instances = [get_problem_from_cnf(CNF(from_file=f)) for f in glob.glob('../Data/uf20-91/*.cnf')]
train_instances, test_instances = instances[:950],instances[950:]

In [9]:
planning_problem = get_problem_from_cnf(CNF(from_file="../Data/blocksworld/medium.cnf"))
network, params = train_model(1000,0.1,[planning_problem], [planning_problem])

step %r loss train %r test %r 0 0.03149056062102318
step %r loss train %r test %r 10 0.03127384930849075
step %r loss train %r test %r 20 0.03126279264688492
step %r loss train %r test %r 30 0.03465767949819565
step %r loss train %r test %r 40 0.14664782583713531


In [12]:
prdictions = network.apply(params, planning_problem.graph)
weights = jax.nn.softmax(prdictions)[: planning_problem.meta["n"], 1]
trajectory, energies = moser_walk_sampler(weights, planning_problem, 1000)

In [15]:
planning_problem.meta

{'n': 122, 'm': 1016, 'k': 6}

In [17]:
weights

DeviceArray([0.9188788 , 0.9188788 , 0.8968981 , 0.95645374, 0.91105783,
             0.9535569 , 0.91105914, 0.95645374, 0.9535569 , 0.91105783,
             0.91105914, 0.94058865, 0.9424409 , 0.94058853, 0.9424408 ,
             0.92849237, 0.81897116, 0.8503994 , 0.8189713 , 0.8503994 ,
             0.98620784, 0.98620784, 0.98620784, 0.98620784, 0.97144204,
             0.995008  , 0.96285427, 0.9927004 , 0.9927005 , 0.9927004 ,
             0.96285486, 0.997832  , 0.9916347 , 0.98827213, 0.9916346 ,
             0.9577119 , 0.9936544 , 0.98827225, 0.98827225, 0.98827225,
             0.940238  , 0.997832  , 0.98827225, 0.9916346 , 0.99163485,
             0.9577119 , 0.982278  , 0.98227787, 0.982278  , 0.98227787,
             0.9761707 , 0.97375613, 0.8189688 , 0.913735  , 0.913735  ,
             0.9137353 , 0.913735  , 0.99733126, 0.99352634, 0.9919173 ,
             0.99352634, 0.99191743, 0.9935266 , 0.9934104 , 0.9935262 ,
             0.99341017, 0.98640186, 0.9473658 , 0.

In [18]:
trajectory

DeviceArray([[ True,  True,  True, ..., False, False, False],
             [ True,  True,  True, ..., False, False, False],
             [ True,  True,  True, ..., False, False, False],
             ...,
             [ True,  True,  True, ..., False, False, False],
             [ True,  True,  True, ..., False, False, False],
             [ True,  True,  True, ..., False, False, False]], dtype=bool)

In [4]:
contradiction = "p cnf 1 1 \n 1 -1 0"
cnf=  CNF(from_string=contradiction)
get_problem_from_cnf(cnf)

Problem(graph=GraphsTuple(nodes=array([[1., 0.],
       [0., 1.]]), edges=array([[0., 1.],
       [1., 0.]]), receivers=array([1, 1]), senders=array([0, 0]), globals=None, n_node=array([2]), n_edge=array([2])), mask=array([1, 0], dtype=int32), meta={'n': 1, 'm': 1, 'k': 2})

In [32]:
from constraint_problems import all_bitstrings
import numpy as np
ass = all_bitstrings(4)
for c in ass:
    print()

In [29]:
np.apply_along_axis(sum, axis=1, arr=all_bitstrings(4))

array([0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3, 2, 3, 3, 4])

In [30]:
from constraint_problems import violated_constraints